---
title: "Base R: Lists"
output: html_notebook
---

##### Let's recap:

* **Vectors** (one dimensional array): can hold numeric, character or logical values. The elements in a vector all have the same data type.
* **Matrices** (two dimensional array): can hold numeric, character or logical values. The elements in a matrix all have the same data type.
* **Data frames** (two-dimensional objects): can hold numeric, character or logical values. Within a column all elements have the same data type, but different columns can be of different data type.

# What are lists in R?
A list in R allows you to gather a variety of objects under one name (that is, the name of the list) in an ordered way. These objects can be matrices, vectors, data frames, even other lists, etc. It is not even required that these objects are related to each other in any way.

A list in R is similar to your to-do list at work or school: the different items on that list most likely differ in length, characteristic, and type of activity that has to be done. You can think of a list as a super data type because you can store practically any piece of information in it

## `list()` in action
```{r example}
# create a vector with numerics 1 through 10
my_vector <- 1:10
my_vector

# create a matrix with numerics 1 through 9
my_matrix <- matrix(1:9, ncol = 3)
my_matrix

# create a df with the first 10 elements of the 'mtcars'
my_df <- mtcars[1:10,]
my_df

# construct a list that contains the variables (my_vector, my_matrix, my_df)
my_list <- list(my_vector, my_matrix, my_df)
my_list
```

